### ISSUE TITLE
v1.1.4 crashes HB

### ISSUE THREAD

**Issue by abolians** [valiquette/homebridge-rachio-irrigation#16]
HB crashes and restarts on a loop after I rebooted my docker container when trying to initialize rachio plugin v1.1.4. reverted back to 1.1.3 and it is working fine.  below is the relevant log 

[9/13/2021, 6:17:08 PM] [Govee] Initializing Govee platform...
[9/13/2021, 6:17:08 PM] [Govee] Initialising plugin v4.10.0 | Node v14.17.3 | HB v1.3.4...
[9/13/2021, 6:17:08 PM] [Rachio] Initializing rachio platform...
[9/13/2021, 6:17:08 PM] [Rachio] Starting Rachio Platform with homebridge API 2.7
[9/13/2021, 6:17:08 PM] TypeError: Cannot read property 'match' of undefined
    at CheckIPaddress (/homebridge/node_modules/homebridge-rachio-irrigation/rachioplatform.js:73:18)
    at new RachioPlatform (/homebridge/node_modules/homebridge-rachio-irrigation/rachioplatform.js:67:16)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
[9/13/2021, 6:17:08 PM] Got SIGTERM, shutting down Homebridge...
[9/13/2021, 6:17:12 PM] [Homebridge UI] Running Command: npm install --save homebridge-rachio-irrigation@1.1.3
[9/13/2021, 6:17:13 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[9/13/2021, 6:17:18 PM] [HB Supervisor] Restarting Homebridge...
[9/13/2021, 6:17:18 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[9/13/2021, 6:17:18 PM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 5331
Initializing HAP-NodeJS v0.9.4...
[9/13/2021, 6:17:19 PM] Loaded config.json with 0 accessories and 7 platforms.
[9/13/2021, 6:17:19 PM] Loaded 46 cached accessories from cachedAccessories.

**Comment by rohair1981** [comment]
I am having the exact same issue. I rolled it back to the previous version and it’s working fine.

**Comment by valiquette** [comment]
Could you copy in your config for this plugins minus your API key?

**Comment by rohair1981** [comment]
"name": "Rachio",
            "api_key": "",
            "default_runtime": 3,
            "use_irrigation_display": true,
            "show_standby": true,
            "show_runall": true,
            "show_schedules": true,
            "external_webhook_port": 12453,
            "internal_webhook_port": 27546,
            "use_basic_auth": false,
            "delete_webhooks": false,
            "platform": "rachio",
            "_bridge": {
                "username": "0E:B9:3E:8F:59:77",
                "port": 53757

**Comment by abolians** [comment]
Here is mine. I tried with and without deleting web hooks 

    "name": "Rachio",
    "api_key": “xxx",
    "default_runtime": 3,
    "use_irrigation_display": true,
    "show_standby": true,
    "show_runall": true,
    "show_schedules": true,
    "external_webhook_port": 12453,
    "internal_webhook_port": 27546,
    "use_basic_auth": false,
    "delete_webhooks": true,
    "platform": "rachio"

**Comment by valiquette** [comment]
I understand what is going on and will correct a few things around this bug. Thanks for reporting this. This is a use case that was not tested when 1.1.4 added support for web hooks to use a web hook relay.   This error stems from not having an external IP address in the config like "external_IP_address": "x.x.x.x".  I would just like to confirm that it is by choice that you are not using the webhook service?

**Comment by rohair1981** [comment]
I wasn’t sure what that was so I didn’t use it. Mine seems to work fine without it.

**Comment by abolians** [comment]
Not using web hooks either 

--Sarmen

**Comment by valiquette** [comment]
Webhooks, provides the return path from Rachio to this plugin. Having it configured keeps everything in sync with any other apps. The readme has more info on that, but it is not necessary.

**Comment by valiquette** [comment]
A fix for the error and how the plugin handle the use case for not having defined anything in the external_IP field. Please let me know it this resolves the issue seen in 1.1.4

**Comment by abolians** [comment]
That was quick. 1.1.5 running with no issues.

[9/14/2021, 2:50:12 PM] [Rachio] Initializing rachio platform...
[9/14/2021, 2:50:12 PM] [Rachio] Starting Rachio Platform with homebridge API 2.7
[9/14/2021, 2:50:12 PM] [Rachio] No external IP or domain name configured, will not configure webhooks. Reference Readme for instructions
[9/14/2021, 2:50:12 PM] [Rachio] Cannot validate webhook destination address, please check webhook config settings. Will not set Webhooks
