### ISSUE TITLE
Update to 1.2.4 fails

### ISSUE THREAD

**Issue by abolians** [valiquette/homebridge-rachio-irrigation#30]
HB 1.3.5 
Node 16.13.0

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/agent.js:114:44)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/socks-proxy-agent/dist/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:161:25)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)

Command failed. Please review log for details.

**Comment by valiquette** [comment]
Can I ask what version of NPM you are running and does the version display correctly on the Homebridge status page. Also have to tried restarting your HB server or forced restart if that applies? I had this same issue with a number of plugins after I upgraded to node 16 and it took a while to figure out it just needed a reboot. Please let me know if this works.

**Comment by abolians** [comment]
I get the same error when I try to execute nom -v 
UI sys info widget reports v8.1.0 
I did several reboots. My NPM install maybe corrupted. Let me try a re install

**Comment by valiquette** [comment]
You can try these steps if you still have an issue, I would reboot after each NPM update.
Downgrade node to 14.18.1
sudo hb-service update-node 14.18.1
Update npm to the latest version 8
sudo npm i -g npm
Update node to 16.13.0
sudo hb-service update-node 16.13.0
Re-update npm to the latest version 8
sudo npm i -g npm
then try re installing the plugin

**Comment by abolians** [comment]
That did it. 
Resolved

THANK YOU!
