### ISSUE TITLE
Address already in use error

### ISSUE THREAD

**Issue by PappyChappy1** [valiquette/homebridge-rachio-irrigation#48]
Hello, trying to get this working, was able to test webhooks and all works, logs seem to pull in my info, but then ultimately crash homebridge completely with this error.  I tried setting up as child bridge and it crashes that as well:
[05/01/2023, 08:19:50] [Rachio] Getting device state info...
Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1485:16)
    at listenInCluster (node:net:1533:12)
    at Server.listen (node:net:1621:7)
    at RachioPlatform.configureListener (/var/lib/homebridge/node_modules/homebridge-rachio-irrigation/rachioplatform.js:554:6)
    at RachioPlatform.getRachioDevices (/var/lib/homebridge/node_modules/homebridge-rachio-irrigation/rachioplatform.js:192:9)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by valiquette** [comment]
It looks like a conflict with the port you are using to forward webhooks messages to. Port 80 (seen in your log) should not be used. You can try using the suggested external 12453 and internal 27543 from the readme file. You can attach you current config if you like.

**Comment by PappyChappy1** [comment]
This worked - thank you.  I assumed I need to use my homebridge port, but leaving the default in and using the same on my port forwarding setup worked.
